# ============================================================
# XR-seq DEVELOPMENTAL RHYTHMICITY
#
# GENERATE GENE-INTRINSIC GENOMIC PREDICTORS
#
# mm10 / GRCm38
#
# ============================================================
#
# Generates:
#
#   gene architecture
#   promoter GC content
#   promoter CpG count/density/O:E
#
# Circadian promoter motifs:
#
#   E-box canonical     CACGTG
#   E-box broad         CANNTG
#   E'-box              CACGTT (+ reverse complement)
#   D-box               TTATGYAA
#   RRE                 WAWNTRGGTCA
#   RORE core           RGGTCA
#
# Windows:
#
#   full promoter       -2000 : +500
#   proximal promoter    -500 : +100
#   distal promoter     -2000 : -501
#
# Coordinates are defined RELATIVE TO TRANSCRIPTION DIRECTION.
#
# ============================================================


# ============================================================
# 0. PACKAGES
# ============================================================

suppressPackageStartupMessages({
  
  library(data.table)
  
  library(GenomicRanges)
  library(IRanges)
  library(S4Vectors)
  library(GenomeInfoDb)
  
  library(rtracklayer)
  library(Rsamtools)
  library(Biostrings)
  
})


# ============================================================
# 1. USER SETTINGS — EDIT THESE
# ============================================================

# ------------------------------------------------------------
# Phenotype directory generated by:
#
# 04_XRseq_build_modeling_phenotypes.R
# ------------------------------------------------------------

PHENOTYPE_DIR <- "limorhyde2_dryR_consensus/modeling_phenotypes"


# ------------------------------------------------------------
# mm10 GTF
#
# IMPORTANT:
# Prefer a GTF containing:
#
#   gene_name
#   gene_id
#   transcript_id
#
# Example:
#
# gencode.vM25.annotation.gtf
#
# ------------------------------------------------------------

GTF_FILE <- "mm10_annotation.gtf"


# ------------------------------------------------------------
# mm10 genome FASTA
#
# Example:
#
# mm10.fa
#
# The script will create .fai if necessary.
# ------------------------------------------------------------

FASTA_FILE <- "mm10.fa"


# ------------------------------------------------------------
# Output
# ------------------------------------------------------------

OUTDIR <- file.path(
  PHENOTYPE_DIR,
  "gene_intrinsic_predictors_mm10"
)


dir.create(
  OUTDIR,
  recursive = TRUE,
  showWarnings = FALSE
)


# ============================================================
# 2. INPUT PHENOTYPE FILES
# ============================================================

MASTER_FILE <- file.path(
  PHENOTYPE_DIR,
  "01_gene_tissue_modeling_dataset.tsv"
)


BINARY_FILE <- file.path(
  PHENOTYPE_DIR,
  "03_remodeling_binary_dataset.tsv"
)


GAIN_LOSS_FILE <- file.path(
  PHENOTYPE_DIR,
  "04_gain_vs_loss_dataset.tsv"
)


TISSUE_SPECIFIC_FILE <- file.path(
  PHENOTYPE_DIR,
  "05_tissue_specific_remodeling_dataset.tsv"
)


required_files <- c(
  
  MASTER_FILE,
  BINARY_FILE,
  GAIN_LOSS_FILE,
  TISSUE_SPECIFIC_FILE,
  GTF_FILE,
  FASTA_FILE
  
)


missing_files <- required_files[
  !file.exists(required_files)
]


if (
  length(missing_files) > 0
) {
  
  stop(
    
    "Missing required files:\n\n",
    
    paste(
      missing_files,
      collapse = "\n"
    )
    
  )
  
}


# ============================================================
# 3. READ PHENOTYPE GENE UNIVERSE
# ============================================================

message("")
message("Reading phenotype gene universe...")


phenotype_master <- fread(
  MASTER_FILE
)


if (
  !"gene" %in%
  names(phenotype_master)
) {
  
  stop(
    "Phenotype master does not contain a gene column."
  )
  
}


target_genes <- sort(
  
  unique(
    
    as.character(
      phenotype_master$gene
    )
    
  )
  
)


message(
  "Unique phenotype genes: ",
  length(target_genes)
)


# ============================================================
# 4. FASTA INDEX
# ============================================================

message("")
message("Checking FASTA index...")


fai_file <- paste0(
  FASTA_FILE,
  ".fai"
)


if (
  !file.exists(fai_file)
) {
  
  message(
    "FASTA index not found."
  )
  
  message(
    "Creating FASTA index..."
  )
  
  
  Rsamtools::indexFa(
    FASTA_FILE
  )
  
}


fa <- Rsamtools::FaFile(
  FASTA_FILE
)


fasta_index <- Rsamtools::scanFaIndex(
  fa
)


fasta_seqnames <- as.character(
  seqnames(
    fasta_index
  )
)


fasta_lengths <- width(
  fasta_index
)


names(
  fasta_lengths
) <- fasta_seqnames


message(
  "FASTA chromosomes/contigs: ",
  length(
    fasta_seqnames
  )
)


# ============================================================
# 5. IMPORT GTF
# ============================================================

message("")
message("Importing GTF...")


gtf <- rtracklayer::import(
  GTF_FILE
)


message(
  "GTF records: ",
  length(gtf)
)


# ============================================================
# 6. GTF ATTRIBUTE HELPERS
# ============================================================

get_gtf_attribute <- function(
    gr,
    candidates,
    required = FALSE
) {
  
  available <- names(
    mcols(gr)
  )
  
  
  hit <- candidates[
    candidates %in%
      available
  ]
  
  
  if (
    length(hit) == 0
  ) {
    
    if (required) {
      
      stop(
        
        "Could not find required GTF attribute.\n",
        
        "Tried:\n",
        
        paste(
          candidates,
          collapse = ", "
        ),
        
        "\n\nAvailable attributes:\n",
        
        paste(
          available,
          collapse = ", "
        )
        
      )
      
    }
    
    
    return(
      rep(
        NA_character_,
        length(gr)
      )
    )
    
  }
  
  
  as.character(mcols(gr)[[hit[1]]])
  
}


gene_symbol <- get_gtf_attribute(
  
  gtf,
  
  c(
    "gene_name",
    "gene",
    "Name",
    "gene_id"
  ),
  
  required = TRUE
  
)


gene_id <- get_gtf_attribute(
  
  gtf,
  
  c(
    "gene_id"
  )
  
)


transcript_id <- get_gtf_attribute(
  
  gtf,
  
  c(
    "transcript_id"
  )
  
)


gene_type <- get_gtf_attribute(
  
  gtf,
  
  c(
    "gene_type",
    "gene_biotype",
    "biotype"
  )
  
)


gtf_type <- get_gtf_attribute(
  
  gtf,
  
  c(
    "type"
  ),
  
  required = TRUE
  
)


# ============================================================
# 7. HARMONIZE CHROMOSOME NAMES TO FASTA
# ============================================================

harmonize_seqname <- function(
    x,
    reference_names
) {
  
  candidates <- x
  
  
  if (
    startsWith(
      x,
      "chr"
    )
  ) {
    
    candidates <- c(
      candidates,
      sub(
        "^chr",
        "",
        x
      )
    )
    
  } else {
    
    candidates <- c(
      candidates,
      paste0(
        "chr",
        x
      )
    )
    
  }
  
  
  if (
    x %in%
    c(
      "M",
      "MT",
      "chrM",
      "chrMT"
    )
  ) {
    
    candidates <- c(
      
      candidates,
      
      "M",
      "MT",
      "chrM",
      "chrMT"
      
    )
    
  }
  
  
  candidates <- unique(
    candidates
  )
  
  
  hit <- candidates[
    candidates %in%
      reference_names
  ]
  
  
  if (
    length(hit) == 0
  ) {
    
    return(
      NA_character_
    )
    
  }
  
  
  hit[1]
  
}


original_seqnames <- as.character(
  seqnames(gtf)
)


mapped_seqnames <- vapply(
  
  original_seqnames,
  
  harmonize_seqname,
  
  character(1),
  
  reference_names =
    fasta_seqnames
  
)


# ============================================================
# 8. GTF DATA TABLE
# ============================================================

gtf_dt <- data.table(
  
  gene =
    gene_symbol,
  
  gene_id =
    gene_id,
  
  transcript_id =
    transcript_id,
  
  gene_type =
    gene_type,
  
  feature_type =
    gtf_type,
  
  chromosome_original =
    original_seqnames,
  
  chromosome =
    mapped_seqnames,
  
  start =
    GenomicRanges::start(
      gtf
    ),
  
  end =
    GenomicRanges::end(
      gtf
    ),
  
  strand =
    as.character(
      GenomicRanges::strand(
        gtf
      )
    )
  
)


rm(gtf)

gc()


# ============================================================
# 9. BASIC ANNOTATION FILTERING
# ============================================================

gtf_dt <- gtf_dt[
  
  !is.na(gene) &
    gene != "" &
    
    gene %in%
    target_genes
  
]


message("")
message(
  "GTF records belonging to phenotype genes: ",
  nrow(gtf_dt)
)


# ============================================================
# 10. CHROMOSOME MAPPING QC
# ============================================================

unmapped_chromosomes <- unique(
  
  gtf_dt[
    is.na(chromosome),
    .(
      chromosome_original
    )
  ]
  
)


fwrite(
  
  unmapped_chromosomes,
  
  file.path(
    OUTDIR,
    "QC_unmapped_GTF_chromosomes.tsv"
  ),
  
  sep = "\t"
  
)


gtf_dt <- gtf_dt[
  !is.na(chromosome)
]


# ============================================================
# 11. HELPER
# ============================================================

first_nonmissing <- function(
    x
) {
  
  x <- x[
    !is.na(x) &
      x != ""
  ]
  
  
  if (
    length(x) == 0
  ) {
    
    return(
      NA_character_
    )
    
  }
  
  
  x[1]
  
}


# ============================================================
# 12. BUILD GENE LOCI
# ============================================================

message("")
message(
  "Building gene loci..."
)


if (
  any(
    gtf_dt$feature_type ==
    "gene"
  )
) {
  
  gene_source <- gtf_dt[
    feature_type ==
      "gene"
  ]
  
  message(
    "Using explicit GTF gene records."
  )
  
} else {
  
  gene_source <- copy(
    gtf_dt
  )
  
  message(
    "No explicit gene records found."
  )
  
  message(
    "Gene loci will be reconstructed from GTF features."
  )
  
}


# ------------------------------------------------------------
# Collapse records belonging to one apparent locus.
# ------------------------------------------------------------

gene_loci <- gene_source[
  ,
  .(
    
    gene_start =
      min(start),
    
    gene_end =
      max(end),
    
    gene_id =
      first_nonmissing(
        gene_id
      ),
    
    gene_type =
      first_nonmissing(
        gene_type
      ),
    
    n_source_records =
      .N
    
  ),
  by = .(
    gene,
    chromosome,
    strand
  )
]


# ============================================================
# 13. IDENTIFY AMBIGUOUS GENE SYMBOLS
# ============================================================

locus_qc <- gene_loci[
  ,
  .(
    n_loci =
      .N
  ),
  by = gene
]


gene_id_qc <- gene_source[
  ,
  .(
    
    n_gene_ids =
      uniqueN(
        
        gene_id[
          !is.na(gene_id) &
            gene_id != ""
        ]
        
      )
    
  ),
  by = gene
]


locus_qc <- merge(
  
  locus_qc,
  
  gene_id_qc,
  
  by =
    "gene",
  
  all =
    TRUE
  
)


locus_qc[
  is.na(n_gene_ids),
  n_gene_ids :=
    0L
]


ambiguous_genes <- locus_qc[
  n_loci > 1 |
    n_gene_ids > 1
]


fwrite(
  
  ambiguous_genes,
  
  file.path(
    OUTDIR,
    "QC_ambiguous_gene_symbols.tsv"
  ),
  
  sep = "\t"
  
)


message(
  "Ambiguous gene symbols excluded: ",
  nrow(
    ambiguous_genes
  )
)


gene_loci <- gene_loci[
  !gene %in%
    ambiguous_genes$gene
]


# ============================================================
# 14. REQUIRE NORMAL STRAND
# ============================================================

invalid_strand <- gene_loci[
  !strand %in%
    c(
      "+",
      "-"
    )
]


fwrite(
  
  invalid_strand,
  
  file.path(
    OUTDIR,
    "QC_invalid_gene_strand.tsv"
  ),
  
  sep = "\t"
  
)


gene_loci <- gene_loci[
  strand %in%
    c(
      "+",
      "-"
    )
]


# ============================================================
# 15. GENE ARCHITECTURE
# ============================================================

gene_arch <- copy(
  gene_loci
)


gene_arch[
  ,
  gene_length_bp :=
    gene_end -
    gene_start +
    1L
]


gene_arch[
  ,
  tss :=
    fifelse(
      
      strand == "+",
      
      gene_start,
      
      gene_end
      
    )
]


# ============================================================
# 16. EXON FEATURES
# ============================================================

message(
  "Calculating exon architecture..."
)


exons <- gtf_dt[
  
  feature_type ==
    "exon" &
    
    gene %in%
    gene_arch$gene
  
]


exons_unique <- unique(
  
  exons[
    ,
    .(
      gene,
      chromosome,
      start,
      end,
      strand
    )
  ]
  
)


if (
  nrow(exons_unique) > 0
) {
  
  exon_features <- exons_unique[
    ,
    .(
      
      n_unique_exons =
        .N,
      
      exonic_union_bp =
        sum(
          
          width(
            
            IRanges::reduce(
              
              IRanges::IRanges(
                start,
                end
              )
              
            )
            
          )
          
        )
      
    ),
    by = gene
  ]
  
} else {
  
  exon_features <- data.table(
    gene = character(),
    n_unique_exons = integer(),
    exonic_union_bp = integer()
  )
  
}


# ============================================================
# 17. TRANSCRIPT FEATURES
# ============================================================

transcript_features <- gtf_dt[
  gene %in%
    gene_arch$gene,
  .(
    
    n_transcripts =
      uniqueN(
        
        transcript_id[
          !is.na(transcript_id) &
            transcript_id != ""
        ]
        
      )
    
  ),
  by = gene
]


# ============================================================
# 18. MERGE ARCHITECTURE FEATURES
# ============================================================

gene_arch <- merge(
  
  gene_arch,
  
  exon_features,
  
  by =
    "gene",
  
  all.x =
    TRUE
  
)


gene_arch <- merge(
  
  gene_arch,
  
  transcript_features,
  
  by =
    "gene",
  
  all.x =
    TRUE
  
)


gene_arch[
  is.na(n_unique_exons),
  n_unique_exons :=
    0L
]


gene_arch[
  is.na(exonic_union_bp),
  exonic_union_bp :=
    0L
]


gene_arch[
  is.na(n_transcripts),
  n_transcripts :=
    0L
]


gene_arch[
  ,
  exonic_fraction_of_gene :=
    exonic_union_bp /
    gene_length_bp
]


gene_arch[
  ,
  non_exonic_gene_body_bp :=
    pmax(
      0,
      gene_length_bp -
        exonic_union_bp
    )
]


# ============================================================
# 19. ANNOTATION MATCH QC
# ============================================================

annotation_match <- data.table(
  
  gene =
    target_genes
  
)


annotation_match[
  ,
  annotation_found :=
    gene %in%
    gene_arch$gene
]


fwrite(
  
  annotation_match,
  
  file.path(
    OUTDIR,
    "QC_gene_annotation_match.tsv"
  ),
  
  sep = "\t"
  
)


fwrite(
  
  annotation_match[
    annotation_found ==
      FALSE
  ],
  
  file.path(
    OUTDIR,
    "QC_unmatched_phenotype_genes.tsv"
  ),
  
  sep = "\t"
  
)


message("")
message(
  "Phenotype genes matched to unique GTF loci: ",
  sum(
    annotation_match$annotation_found
  ),
  " / ",
  nrow(
    annotation_match
  )
)


# ============================================================
# 20. KEEP MATCHED GENES
# ============================================================

gene_arch <- gene_arch[
  gene %in%
    target_genes
]


setorder(
  gene_arch,
  gene
)


# ============================================================
# 21. PROMOTER WINDOW HELPER
#
# rel_start / rel_end are coordinates relative to TSS
# in TRANSCRIPTION DIRECTION.
# ============================================================

make_relative_window <- function(
    genes,
    rel_start,
    rel_end,
    label
) {
  
  if (
    rel_start >
    rel_end
  ) {
    
    stop(
      "rel_start must be <= rel_end."
    )
    
  }
  
  
  x <- genes[
    ,
    .(
      gene,
      chromosome,
      strand,
      tss
    )
  ]
  
  
  x[
    strand == "+",
    untrimmed_start :=
      tss +
      rel_start
  ]
  
  
  x[
    strand == "+",
    untrimmed_end :=
      tss +
      rel_end
  ]
  
  
  x[
    strand == "-",
    untrimmed_start :=
      tss -
      rel_end
  ]
  
  
  x[
    strand == "-",
    untrimmed_end :=
      tss -
      rel_start
  ]
  
  
  x[
    ,
    chromosome_length :=
      as.integer(
        fasta_lengths[
          chromosome
        ]
      )
  ]
  
  
  if (
    anyNA(
      x$chromosome_length
    )
  ) {
    
    stop(
      "Some gene chromosomes were not found in FASTA."
    )
    
  }
  
  
  x[
    ,
    genomic_start :=
      pmax(
        1L,
        untrimmed_start
      )
  ]
  
  
  x[
    ,
    genomic_end :=
      pmin(
        chromosome_length,
        untrimmed_end
      )
  ]
  
  
  if (
    any(
      x$genomic_start >
      x$genomic_end
    )
  ) {
    
    stop(
      "Invalid promoter interval after chromosome clipping."
    )
    
  }
  
  
  x[
    ,
    clipped :=
      genomic_start !=
      untrimmed_start |
      genomic_end !=
      untrimmed_end
  ]
  
  
  x[
    ,
    expected_width :=
      rel_end -
      rel_start +
      1L
  ]
  
  
  x[
    ,
    actual_width :=
      genomic_end -
      genomic_start +
      1L
  ]
  
  
  gr <- GenomicRanges::GRanges(
    
    seqnames =
      x$chromosome,
    
    ranges =
      IRanges::IRanges(
        
        start =
          x$genomic_start,
        
        end =
          x$genomic_end
        
      ),
    
    strand =
      "*"
    
  )
  
  
  names(gr) <-
    x$gene
  
  
  list(
    
    label =
      label,
    
    info =
      x,
    
    gr =
      gr
    
  )
  
}


# ============================================================
# 22. DEFINE PROMOTER WINDOWS
# ============================================================

full_window <- make_relative_window(
  
  gene_arch,
  
  rel_start =
    -2000,
  
  rel_end =
    500,
  
  label =
    "full"
  
)


proximal_window <- make_relative_window(
  
  gene_arch,
  
  rel_start =
    -500,
  
  rel_end =
    100,
  
  label =
    "proximal"
  
)


# Non-overlapping with proximal promoter.
distal_window <- make_relative_window(
  
  gene_arch,
  
  rel_start =
    -2000,
  
  rel_end =
    -501,
  
  label =
    "distal"
  
)


# ============================================================
# 23. PROMOTER WINDOW QC
# ============================================================

window_qc <- rbindlist(
  
  list(
    
    full_window$info[
      ,
      window :=
        "full_-2000_to_+500"
    ],
    
    proximal_window$info[
      ,
      window :=
        "proximal_-500_to_+100"
    ],
    
    distal_window$info[
      ,
      window :=
        "distal_-2000_to_-501"
    ]
    
  ),
  
  fill = TRUE
  
)


fwrite(
  
  window_qc,
  
  file.path(
    OUTDIR,
    "QC_promoter_windows.tsv"
  ),
  
  sep = "\t"
  
)


message(
  "Clipped promoter windows: ",
  sum(
    window_qc$clipped
  ),
  " / ",
  nrow(
    window_qc
  )
)


# ============================================================
# 24. EXTRACT ORIENTED PROMOTER SEQUENCES
# ============================================================

extract_oriented_sequence <- function(
    window_object
) {
  
  seqs <- Rsamtools::scanFa(
    
    fa,
    
    param =
      window_object$gr
    
  )
  
  
  names(seqs) <-
    window_object$info$gene
  
  
  minus <- window_object$info$strand ==
    "-"
  
  
  if (
    any(minus)
  ) {
    
    seqs[
      minus
    ] <- Biostrings::reverseComplement(
      
      seqs[
        minus
      ]
      
    )
    
  }
  
  
  seqs
  
}


message("")
message(
  "Extracting full promoters..."
)


seq_full <- extract_oriented_sequence(
  full_window
)


message(
  "Extracting proximal promoters..."
)


seq_proximal <- extract_oriented_sequence(
  proximal_window
)


message(
  "Extracting distal promoters..."
)


seq_distal <- extract_oriented_sequence(
  distal_window
)


# ============================================================
# 25. SAVE PROMOTER FASTA FILES
# ============================================================

Biostrings::writeXStringSet(
  
  seq_full,
  
  filepath =
    file.path(
      OUTDIR,
      "promoter_full_minus2000_plus500.fa"
    )
  
)


Biostrings::writeXStringSet(
  
  seq_proximal,
  
  filepath =
    file.path(
      OUTDIR,
      "promoter_proximal_minus500_plus100.fa"
    )
  
)


Biostrings::writeXStringSet(
  
  seq_distal,
  
  filepath =
    file.path(
      OUTDIR,
      "promoter_distal_minus2000_minus501.fa"
    )
  
)


# ============================================================
# 26. MOTIF DEFINITIONS
# ============================================================

motifs <- data.table(
  
  feature_name = c(
    
    "ebox_CANNTG",
    
    "ebox_CACGTG",
    
    "ebox_Eprime_CACGTT",
    
    "dbox_TTATGYAA",
    
    "rre_WAWNTRGGTCA",
    
    "rore_core_RGGTCA"
    
  ),
  
  pattern = c(
    
    "CANNTG",
    
    "CACGTG",
    
    "CACGTT",
    
    "TTATGYAA",
    
    "WAWNTRGGTCA",
    
    "RGGTCA"
    
  ),
  
  description = c(
    
    "General E-box",
    
    "Canonical CLOCK/BMAL1-preferred E-box",
    
    "E-prime-like CACGTT motif",
    
    "Circadian D-box consensus",
    
    "Extended circadian RRE consensus",
    
    "RORE/RRE core"
    
  )
  
)


motifs[
  ,
  reverse_complement :=
    vapply(
      
      pattern,
      
      function(x) {
        
        as.character(
          
          Biostrings::reverseComplement(
            
            Biostrings::DNAString(
              x
            )
            
          )
          
        )
        
      },
      
      character(1)
      
    )
]


fwrite(
  
  motifs,
  
  file.path(
    OUTDIR,
    "motif_definitions.tsv"
  ),
  
  sep = "\t"
  
)


# ============================================================
# 27. COUNT MOTIF ON BOTH DNA ORIENTATIONS
# ============================================================

count_motif_both_strands <- function(
    seqs,
    pattern
) {
  
  rc <- as.character(
    
    Biostrings::reverseComplement(
      
      Biostrings::DNAString(
        pattern
      )
      
    )
    
  )
  
  
  forward_count <- Biostrings::vcountPattern(
    
    pattern =
      pattern,
    
    subject =
      seqs,
    
    fixed =
      "subject"
    
  )
  
  
  # Avoid double counting palindromic/self-RC motifs.
  if (
    identical(
      pattern,
      rc
    )
  ) {
    
    return(
      as.integer(
        forward_count
      )
    )
    
  }
  
  
  reverse_count <- Biostrings::vcountPattern(
    
    pattern =
      rc,
    
    subject =
      seqs,
    
    fixed =
      "subject"
    
  )
  
  
  as.integer(
    forward_count +
      reverse_count
  )
  
}


# ============================================================
# 28. CALCULATE SEQUENCE FEATURES
# ============================================================

calculate_sequence_features <- function(
    seqs,
    prefix
) {
  
  nucleotide_counts <- Biostrings::letterFrequency(
    
    seqs,
    
    letters = c(
      "A",
      "C",
      "G",
      "T"
    ),
    
    as.prob =
      FALSE
    
  )
  
  
  valid_bp <- rowSums(
    nucleotide_counts
  )
  
  
  total_bp <- width(
    seqs
  )
  
  
  cpg_count <- as.integer(
    
    Biostrings::vcountPattern(
      
      "CG",
      
      seqs,
      
      fixed = TRUE
      
    )
    
  )
  
  
  result <- data.table(
    
    gene =
      names(seqs),
    
    sequence_width_bp =
      as.integer(
        total_bp
      ),
    
    valid_ACGT_bp =
      as.integer(
        valid_bp
      ),
    
    ambiguous_bp =
      as.integer(
        total_bp -
          valid_bp
      ),
    
    A_count =
      nucleotide_counts[
        ,
        "A"
      ],
    
    C_count =
      nucleotide_counts[
        ,
        "C"
      ],
    
    G_count =
      nucleotide_counts[
        ,
        "G"
      ],
    
    T_count =
      nucleotide_counts[
        ,
        "T"
      ],
    
    GC_percent =
      fifelse(
        
        valid_bp > 0,
        
        100 *
          (
            nucleotide_counts[
              ,
              "G"
            ] +
              nucleotide_counts[
                ,
                "C"
              ]
          ) /
          valid_bp,
        
        NA_real_
        
      ),
    
    CpG_count =
      cpg_count,
    
    CpG_per_kb =
      fifelse(
        
        valid_bp > 0,
        
        cpg_count /
          (
            valid_bp /
              1000
          ),
        
        NA_real_
        
      ),
    
    CpG_observed_expected =
      fifelse(
        
        nucleotide_counts[
          ,
          "C"
        ] > 0 &
          
          nucleotide_counts[
            ,
            "G"
          ] > 0,
        
        cpg_count *
          valid_bp /
          (
            nucleotide_counts[
              ,
              "C"
            ] *
              nucleotide_counts[
                ,
                "G"
              ]
          ),
        
        NA_real_
        
      )
    
  )
  
  
  # ----------------------------------------------------------
  # Motif features
  # ----------------------------------------------------------
  
  for (
    i in seq_len(
      nrow(motifs)
    )
  ) {
    
    motif_name <-
      motifs$feature_name[i]
    
    
    motif_pattern <-
      motifs$pattern[i]
    
    
    motif_count <- count_motif_both_strands(
      
      seqs =
        seqs,
      
      pattern =
        motif_pattern
      
    )
    
    
    result[
      ,
      (paste0(
        motif_name,
        "_count"
      )) :=
        motif_count
    ]
    
    
    result[
      ,
      (paste0(
        motif_name,
        "_per_kb"
      )) :=
        fifelse(
          
          valid_bp > 0,
          
          motif_count /
            (
              valid_bp /
                1000
            ),
          
          NA_real_
          
        )
    ]
    
  }
  
  
  # ----------------------------------------------------------
  # Canonical E-box fraction
  #
  # Among all CANNTG sites, what fraction are CACGTG?
  # ----------------------------------------------------------
  
  result[
    ,
    ebox_canonical_fraction :=
      fifelse(
        
        ebox_CANNTG_count >
          0,
        
        ebox_CACGTG_count /
          ebox_CANNTG_count,
        
        0
        
      )
  ]
  
  
  # ----------------------------------------------------------
  # Prefix all feature names except gene.
  # ----------------------------------------------------------
  
  feature_columns <- setdiff(
    names(result),
    "gene"
  )
  
  
  setnames(
    
    result,
    
    feature_columns,
    
    paste0(
      prefix,
      "_",
      feature_columns
    )
    
  )
  
  
  result
  
}


# ============================================================
# 29. CALCULATE ALL THREE WINDOWS
# ============================================================

message("")
message(
  "Calculating full-promoter features..."
)


features_full <- calculate_sequence_features(
  
  seq_full,
  
  prefix =
    "full"
)


message(
  "Calculating proximal-promoter features..."
)


features_proximal <- calculate_sequence_features(
  
  seq_proximal,
  
  prefix =
    "proximal"
)


message(
  "Calculating distal-promoter features..."
)


features_distal <- calculate_sequence_features(
  
  seq_distal,
  
  prefix =
    "distal"
)


# ============================================================
# 30. PROMOTER COORDINATE METADATA
# ============================================================

window_metadata <- full_window$info[
  ,
  .(
    
    gene,
    
    full_promoter_start =
      genomic_start,
    
    full_promoter_end =
      genomic_end,
    
    full_promoter_clipped =
      clipped
    
  )
]


window_metadata <- merge(
  
  window_metadata,
  
  proximal_window$info[
    ,
    .(
      
      gene,
      
      proximal_promoter_start =
        genomic_start,
      
      proximal_promoter_end =
        genomic_end,
      
      proximal_promoter_clipped =
        clipped
      
    )
  ],
  
  by =
    "gene",
  
  all =
    TRUE
  
)


window_metadata <- merge(
  
  window_metadata,
  
  distal_window$info[
    ,
    .(
      
      gene,
      
      distal_promoter_start =
        genomic_start,
      
      distal_promoter_end =
        genomic_end,
      
      distal_promoter_clipped =
        clipped
      
    )
  ],
  
  by =
    "gene",
  
  all =
    TRUE
  
)


# ============================================================
# 31. BUILD FINAL GENE-INTRINSIC PREDICTOR TABLE
# ============================================================

predictors <- merge(
  
  gene_arch,
  
  window_metadata,
  
  by =
    "gene",
  
  all.x =
    TRUE
  
)


predictors <- merge(
  
  predictors,
  
  features_full,
  
  by =
    "gene",
  
  all.x =
    TRUE
  
)


predictors <- merge(
  
  predictors,
  
  features_proximal,
  
  by =
    "gene",
  
  all.x =
    TRUE
  
)


predictors <- merge(
  
  predictors,
  
  features_distal,
  
  by =
    "gene",
  
  all.x =
    TRUE
  
)


setorder(
  predictors,
  gene
)


# ============================================================
# 32. FINAL FEATURE QC
# ============================================================

predictors[
  ,
  any_missing_sequence_features :=
    is.na(
      full_GC_percent
    ) |
    is.na(
      proximal_GC_percent
    ) |
    is.na(
      distal_GC_percent
    )
]


predictors[
  ,
  any_promoter_clipping :=
    full_promoter_clipped |
    proximal_promoter_clipped |
    distal_promoter_clipped
]


message("")
message(
  "Final predictor genes: ",
  nrow(predictors)
)


message(
  "Genes with clipped promoter window: ",
  sum(
    predictors$any_promoter_clipping,
    na.rm = TRUE
  )
)


message(
  "Genes with missing sequence features: ",
  sum(
    predictors$any_missing_sequence_features,
    na.rm = TRUE
  )
)


# ============================================================
# 33. WRITE MAIN PREDICTOR TABLE
# ============================================================

PREDICTOR_FILE <- file.path(
  
  OUTDIR,
  
  "gene_intrinsic_predictors_mm10.tsv"
  
)


fwrite(
  
  predictors,
  
  PREDICTOR_FILE,
  
  sep = "\t"
  
)


# ============================================================
# 34. FEATURE MANIFEST
#
# Marks metadata/QC vs candidate predictors.
# ============================================================

feature_manifest <- data.table(
  
  feature =
    names(predictors)
  
)


feature_manifest[
  ,
  role :=
    "candidate_predictor"
]


feature_manifest[
  feature %in%
    c(
      "gene",
      "gene_id",
      "chromosome",
      "gene_start",
      "gene_end",
      "tss",
      "n_source_records"
    ),
  role :=
    "metadata"
]


feature_manifest[
  grepl(
    "_promoter_start$|_promoter_end$",
    feature
  ),
  role :=
    "metadata"
]


feature_manifest[
  grepl(
    "clipped|missing",
    feature
  ),
  role :=
    "QC"
]


fwrite(
  
  feature_manifest,
  
  file.path(
    OUTDIR,
    "feature_manifest.tsv"
  ),
  
  sep = "\t"
  
)


# ============================================================
# 35. HELPER TO MERGE PREDICTORS INTO MODELING DATASET
# ============================================================

merge_predictors <- function(
    phenotype_file,
    keep_columns,
    output_name
) {
  
  x <- fread(
    phenotype_file
  )
  
  
  missing_cols <- setdiff(
    keep_columns,
    names(x)
  )
  
  
  if (
    length(missing_cols) > 0
  ) {
    
    stop(
      
      "Missing columns in:\n",
      phenotype_file,
      "\n\n",
      
      paste(
        missing_cols,
        collapse = ", "
      )
      
    )
    
  }
  
  
  x <- x[
    ,
    ..keep_columns
  ]
  
  
  out <- merge(
    
    x,
    
    predictors,
    
    by =
      "gene",
    
    all.x =
      TRUE,
    
    sort =
      FALSE
    
  )
  
  
  out[
    ,
    genomic_predictors_available :=
      !is.na(
        gene_length_bp
      )
  ]
  
  
  fwrite(
    
    out,
    
    file.path(
      OUTDIR,
      output_name
    ),
    
    sep = "\t"
    
  )
  
  
  out
  
}


# ============================================================
# 36. ML-READY BINARY TABLE
# ============================================================

binary_predictors <- merge_predictors(
  
  phenotype_file =
    BINARY_FILE,
  
  keep_columns =
    c(
      "gene",
      "tissue",
      "group_id",
      "target_remodeled",
      "target_label"
    ),
  
  output_name =
    "ML_binary_remodeling_with_genomic_predictors.tsv"
  
)


# ============================================================
# 37. ML-READY GAIN vs LOSS TABLE
# ============================================================

gain_loss_predictors <- merge_predictors(
  
  phenotype_file =
    GAIN_LOSS_FILE,
  
  keep_columns =
    c(
      "gene",
      "tissue",
      "group_id",
      "target_gain",
      "target_direction"
    ),
  
  output_name =
    "ML_gain_vs_loss_with_genomic_predictors.tsv"
  
)


# ============================================================
# 38. ML-READY TISSUE-SPECIFIC TABLE
# ============================================================

tissue_specific_predictors <- merge_predictors(
  
  phenotype_file =
    TISSUE_SPECIFIC_FILE,
  
  keep_columns =
    c(
      "gene",
      "tissue",
      "group_id",
      "target_remodeled_in_tissue",
      "target_tissue_state"
    ),
  
  output_name =
    "ML_tissue_specific_with_genomic_predictors.tsv"
  
)


# ============================================================
# 39. PREDICTOR AVAILABILITY QC
# ============================================================

predictor_availability <- data.table(
  
  dataset = c(
    
    "binary_remodeling",
    
    "gain_vs_loss",
    
    "tissue_specific"
    
  ),
  
  n_rows = c(
    
    nrow(
      binary_predictors
    ),
    
    nrow(
      gain_loss_predictors
    ),
    
    nrow(
      tissue_specific_predictors
    )
    
  ),
  
  n_rows_with_predictors = c(
    
    sum(
      binary_predictors$
        genomic_predictors_available
    ),
    
    sum(
      gain_loss_predictors$
        genomic_predictors_available
    ),
    
    sum(
      tissue_specific_predictors$
        genomic_predictors_available
    )
    
  ),
  
  n_unique_genes = c(
    
    uniqueN(
      binary_predictors$gene
    ),
    
    uniqueN(
      gain_loss_predictors$gene
    ),
    
    uniqueN(
      tissue_specific_predictors$gene
    )
    
  )
  
)


predictor_availability[
  ,
  percent_rows_with_predictors :=
    100 *
    n_rows_with_predictors /
    n_rows
]


fwrite(
  
  predictor_availability,
  
  file.path(
    OUTDIR,
    "QC_predictor_availability.tsv"
  ),
  
  sep = "\t"
  
)


# ============================================================
# 40. SUMMARY OF NUMERIC PREDICTORS
# ============================================================

numeric_columns <- names(predictors)[
  
  vapply(
    predictors,
    is.numeric,
    logical(1)
  )
  
]


numeric_summary <- rbindlist(
  
  lapply(
    
    numeric_columns,
    
    function(column_name) {
      
      x <- predictors[[column_name]]
      
      
      data.table(
        
        feature =
          column_name,
        
        n =
          sum(
            !is.na(x)
          ),
        
        n_missing =
          sum(
            is.na(x)
          ),
        
        mean =
          mean(
            x,
            na.rm = TRUE
          ),
        
        sd =
          sd(
            x,
            na.rm = TRUE
          ),
        
        median =
          median(
            x,
            na.rm = TRUE
          ),
        
        min =
          min(
            x,
            na.rm = TRUE
          ),
        
        max =
          max(
            x,
            na.rm = TRUE
          )
        
      )
      
    }
    
  )
  
)


fwrite(
  
  numeric_summary,
  
  file.path(
    OUTDIR,
    "QC_numeric_predictor_summary.tsv"
  ),
  
  sep = "\t"
  
)


# ============================================================
# 41. SESSION INFO
# ============================================================

capture.output(
  
  sessionInfo(),
  
  file =
    file.path(
      OUTDIR,
      "sessionInfo.txt"
    )
  
)


# ============================================================
# 42. FINAL SUMMARY
# ============================================================

message("")
message(
  "===================================================="
)

message(
  "GENOMIC PREDICTOR GENERATION COMPLETE"
)

message(
  "===================================================="
)


message("")
message(
  "Genes requested: ",
  length(
    target_genes
  )
)


message(
  "Genes with genomic predictors: ",
  nrow(
    predictors
  )
)


message("")
message(
  "Main gene-level predictor table:"
)

message(
  PREDICTOR_FILE
)


message("")
message(
  "ML-ready binary dataset:"
)

message(
  
  file.path(
    OUTDIR,
    "ML_binary_remodeling_with_genomic_predictors.tsv"
  )
  
)


message("")
message(
  "ML-ready gain/loss dataset:"
)

message(
  
  file.path(
    OUTDIR,
    "ML_gain_vs_loss_with_genomic_predictors.tsv"
  )
  
)


message("")
message(
  "ML-ready tissue-specific dataset:"
)

message(
  
  file.path(
    OUTDIR,
    "ML_tissue_specific_with_genomic_predictors.tsv"
  )
  
)


message("")
message(
  "Predictor availability:"
)

print(
  predictor_availability
)

message("")
message(
  "Done."
)